import { describe, it, expect } from "vitest";
import * as XLSX from "xlsx";
import fs from "node:fs";
import { readCheckTime } from "./checktime-reader";

const REAL = "c:/Users/USER/OneDrive/Desktop/TungLam/Exports from Million/CHECKTIME_InOutReportAll.xlsx";

/** Build a miniature CheckTime export with the same shape as the real one. */
function fakeExport(dataRows: unknown[][]): Buffer {
  const header = [
    "EMP ID", null, "Name", null, null, "Department", null, "Date",
    "Check In 1", "Check Out 1", "Check In 2", "Check Out 2", "Check In 3", "Check Out 3",
    "Check In 4", "Check Out 4", "Check In 5", "Check Out 5", "Check In 6", "Check Out 6",
    "Check In 7", "Check Out 7", "Check In 8", "Check Out 8", "Check In 9", "Check Out 9",
    "Check In 10", "Check Out 10", null, "Total Hours", "Location",
  ];
  const aoa = [["In Out Report"], [], [], [], [], [], header, ...dataRows];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(aoa), "InOutReportAll");
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

const row = (id: string, name: string, date: string, ...punches: (string | null)[]) => {
  const r: (string | null)[] = [id, null, name, null, null, "Tung Lam", null, date];
  for (let i = 0; i < 20; i++) r.push(punches[i] ?? null);
  r.push(null, "00:00", "xface100-0181");
  return r;
};

describe("readCheckTime", () => {
  it("turns a scan row into a worker, a date and its punches", () => {
    const rows = readCheckTime(
      fakeExport([row("2028", "ISLAM MD NORUL", "02/06/2026", "07:06", "20:24")]),
    );
    expect(rows).toEqual([
      { scannerId: "2028", name: "ISLAM MD NORUL", date: "2026-06-02", punches: ["07:06", "20:24"] },
    ]);
  });

  it("converts the scanner's day-first dates to ISO", () => {
    const rows = readCheckTime(fakeExport([row("2028", "X", "14/08/2026", "07:00", "19:00")]));
    expect(rows[0].date).toBe("2026-08-14");
  });

  it("keeps every punch in scan order, including the middle ones", () => {
    const rows = readCheckTime(
      fakeExport([row("81", "X", "14/09/2025", "07:23", "12:24", "20:24")]),
    );
    expect(rows[0].punches).toEqual(["07:23", "12:24", "20:24"]);
  });

  it("keeps a single punch rather than dropping the row", () => {
    const rows = readCheckTime(fakeExport([row("18", "X", "08/09/2025", "17:08")]));
    expect(rows[0].punches).toEqual(["17:08"]);
  });

  it("pads scanner IDs so 18 and 0018 are the same worker", () => {
    const rows = readCheckTime(fakeExport([row("0018", "X", "08/09/2025", "07:00", "19:00")]));
    expect(rows[0].scannerId).toBe("18");
  });

  it("skips rows with no employee ID", () => {
    expect(readCheckTime(fakeExport([row("", "", "", null)]))).toHaveLength(0);
  });

  it("says plainly what is wrong when given the wrong file", () => {
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([["Not", "a", "report"]]), "Sheet1");
    const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
    expect(() => readCheckTime(buf)).toThrow(/CheckTime/);
  });

  it("ignores the footer line the scanner writes under the data", () => {
    const rows = readCheckTime(
      fakeExport([
        row("2028", "X", "02/06/2026", "07:00", "19:00"),
        ["This Report Generated by 'Check-Time Attendance Management Software'"],
      ]),
    );
    expect(rows).toHaveLength(1);
  });

  it("reads the real export from the factory", () => {
    const rows = readCheckTime(fs.readFileSync(REAL));
    // 2,100 rows carry an employee ID, but the last is the software's own
    // footer line sitting in that column, not a scan.
    expect(rows.length).toBe(2099);
    expect(new Set(rows.map((r) => r.scannerId)).size).toBe(55);
    // The scanner's own Total Hours said 05:01 for this day. We keep all three
    // punches so the real span, 07:23 to 20:24, can be worked out.
    const sep14 = rows.find((r) => r.scannerId === "81" && r.date === "2025-09-14");
    expect(sep14!.punches).toEqual(["07:23", "12:24", "20:24"]);
  });
});
